market: KR

symbols:
  indices:
    - symbol: "069500"
      name: "KODEX 200"
      type: "etf_main"
      group: "core"
    - symbol: "102110"
      name: "TIGER 200"
      type: "etf_main"
      group: "core"

  leverage:
    - symbol: "122630"
      name: "KODEX 레버리지 (2x)"
      type: "etf_leverage"
      group: "core"
    - symbol: "252670"
      name: "KODEX 200선물인버스2X (-2x)"
      type: "etf_leverage"
      group: "core"
    - symbol: "233740"
      name: "KODEX 코스닥150레버리지"
      type: "etf_leverage"
      group: "core"

  sectors:
    # Core Sectors (KIS Tick + Kiwoom Orderbook)
    semiconductor:
      group: "core"
      etf:
        symbol: "091230"
        name: "TIGER 반도체"
      top3:
        - symbol: "005930"
          name: "삼성전자"
        - symbol: "000660"
          name: "SK하이닉스"
        - symbol: "042700"
          name: "한미반도체"
        - symbol: "005935"
          name: "삼성전자우"
    
    battery:
      group: "core"
      etf:
        symbol: "305540"
        name: "TIGER 2차전지테마"
      top3:
        - symbol: "373220"
          name: "LG에너지솔루션"
        - symbol: "006400"
          name: "삼성SDI"
        - symbol: "005490"
          name: "POSCO홀딩스"
        - symbol: "051910"
          name: "LG화학"
        - symbol: "247540"
          name: "에코프로비엠"
        - symbol: "086520"
          name: "에코프로"
        - symbol: "003670"
          name: "포스코퓨처엠"
        - symbol: "096770"
          name: "SK이노베이션"

    biotech:
      group: "core"
      etf:
        symbol: "091210"
        name: "TIGER 헬스케어"
      top3:
        - symbol: "207940"
          name: "삼성바이오로직스"
        - symbol: "068270"
          name: "셀트리온"
        - symbol: "000100"
          name: "유한양행"
        - symbol: "128940"
          name: "한미약품"
        - symbol: "028300"
          name: "HLB"
    
    auto:
      group: "core"
      etf:
        symbol: "091180"
        name: "KODEX 자동차"
      top3:
        - symbol: "005380"
          name: "현대차"
        - symbol: "000270"
          name: "기아"
        - symbol: "012330"
          name: "현대모비스"

    ict_service:
      group: "core"
      top3:
        - symbol: "035420"
          name: "NAVER"
        - symbol: "035720"
          name: "Kakao"
        - symbol: "018260"
          name: "삼성에스디에스"
        - symbol: "011070"
          name: "LG이노텍"

    finance:
      group: "core"
      top3:
        - symbol: "105560"
          name: "KB금융"
        - symbol: "055550"
          name: "신한지주"
        - symbol: "086790"
          name: "하나금융지주"
        - symbol: "032830"
          name: "삼성생명"

    # Rotation Sectors (Kiwoom Tick + Kiwoom Orderbook)
    defense:
      group: "rotation"
      top3:
        - symbol: "012450"
          name: "한화에어로스페이스"
        - symbol: "079550"
          name: "LIG넥스원"
        - symbol: "064350"
          name: "현대로템"
        - symbol: "000880"
          name: "한화"

    heavy_industry:
      group: "rotation"
      top3:
        - symbol: "042660"
          name: "한화오션"
        - symbol: "015760"
          name: "한국전력"
        - symbol: "009540"
          name: "HD한국조선해양"
        - symbol: "034020"
          name: "두산에너빌리티"
        - symbol: "010130"
          name: "고려아연"
        - symbol: "003490"
          name: "대한항공"
        - symbol: "277810"
          name: "레인보우로보틱스"

    power_energy:
      group: "rotation"
      top3:
        - symbol: "010120"
          name: "LS ELECTRIC"
        - symbol: "298040"
          name: "효성중공업"
        - symbol: "267260"
          name: "HD현대일렉트릭"
        - symbol: "000720"
          name: "현대건설"

    ship_logis:
      group: "rotation"
      top3:
        - symbol: "329180"
          name: "HD현대중공업"
        - symbol: "010140"
          name: "삼성중공업"
        - symbol: "011200"
          name: "HMM"
        - symbol: "010620"
          name: "현대미포조선"

    food_beverage:
      group: "rotation"
      top3:
        - symbol: "003230"
          name: "삼양식품"
        - symbol: "004370"
          name: "농심"
        - symbol: "097950"
          name: "CJ제일제당"
        - symbol: "001680"
          name: "대상"

    cosmetic_medical:
      group: "rotation"
      top3:
        - symbol: "090430"
          name: "아모레퍼시픽"
        - symbol: "257720"
          name: "실리콘투"
        - symbol: "051900"
          name: "LG생활건강"
        - symbol: "192080"
          name: "더네이쳐홀딩스"
        - symbol: "102460"
          name: "이연제약"

    ent_game:
      group: "rotation"
      top3:
        - symbol: "352820"
          name: "하이브"
        - symbol: "259960"
          name: "크래프톤"
        - symbol: "041510"
          name: "에스엠"
        - symbol: "035900"
          name: "JYP Ent."
        - symbol: "036570"
          name: "NC소프트"
        - symbol: "251270"
          name: "넷마블"

    robot_ai:
      group: "rotation"
      top3:
        - symbol: "454910"
          name: "두산로보틱스"
        - symbol: "304100"
          name: "솔루엠"
        - symbol: "383310"
          name: "에코프로에이치엔"
        - symbol: "403490"
          name: "루닛"

    raw_mat_util:
      group: "rotation"
      top3:
        - symbol: "011780"
          name: "금호석유"
        - symbol: "047050"
          name: "포스코인터내셔널"
        - symbol: "000670"
          name: "영풍"
        - symbol: "010060"
          name: "OCI홀딩스"
        - symbol: "009830"
          name: "한화솔루션"

    construction_infra:
      group: "rotation"
      top3:
        - symbol: "028050"
          name: "삼성엔지니어링"
        - symbol: "006360"
          name: "GS건설"
        - symbol: "000210"
          name: "DL이앤씨"

    bio_rotation:
      group: "rotation"
      top3:
        - symbol: "196170"
          name: "알테오젠"
        - symbol: "141080"
          name: "리그켐바이오"
        - symbol: "237690"
          name: "에스티팜"
        - symbol: "068760"
          name: "셀트리온제약"

    finance_holding:
      group: "rotation"
      top3:
        - symbol: "008560"
          name: "메리츠금융지주"
        - symbol: "028260"
          name: "삼성물산"
        - symbol: "000030"
          name: "우리금융지주"
        - symbol: "034730"
          name: "SK"

    retail_tech:
      group: "rotation"
      top3:
        - symbol: "028230"
          name: "BGF리테일"
        - symbol: "240810"
          name: "원익IPS"
        - symbol: "357780"
          name: "솔브레인"
        - symbol: "032640"
          name: "LG유플러스"

    etf_special:
      group: "rotation"
      top3:
        - symbol: "143850"
          name: "TIGER 미국S&P500"
        - symbol: "133690"
          name: "TIGER 미국나스닥100"
        - symbol: "152380"
          name: "KODEX 국고채10년"
        - symbol: "225130"
          name: "KODEX 골드선물(H)"
